### ISSUE TITLE
Get-BinRoot not getting chocolatey bin root

### ISSUE THREAD

**Issue by masaeedu** [OneGet/OldNuGetProvider#1]
I've been having issues installing cygwin using the chocolatey provider. The actual execution of the installer seems to error out with exit code 1. I believe the issue comes down to the following step (from a `-Debug` step through of the installation)

```
VERBOSE: StartChocolateyProcessAsAdmin «Exe '{0}', Args '{1}'»
«C:\Users\MyName\AppData\Local\Temp\chocolatey\Cygwin\Cygwininstall.exe» «-q -R  -l  -s
http://mirrors.kernel.org/sourceware/cygwin/»
```

The relevant bit of the install script is the following:

```
$binRoot = Get-BinRoot
$cygRoot = join-path $binRoot "cygwin"
$cygPackages = join-path $cygRoot packages

# https://cygwin.com/faq/faq.html#faq.setup.cli
$silentArgs = "-q -R $cygRoot -l $cygPackages -s http://mirrors.kernel.org/sourceware/cygwin/"
$validExitCodes = @(0)

Install-ChocolateyPackage "$packageName" "$installerType" "$silentArgs" "$url" "$url64"  -validExitCodes $validExitCodes
$installerFile = join-path $env:Temp 'chocolatey\cygwin\cygwinInstall.exe'
```

The important bit is the `Get-BinRoot` call in the first line. I believe (but don't know how to confirm) that `Get-BinRoot` is broken, and is not returning `C:\Chocolatey\bin` as would the current official version of chocolatey. The hint pointing to this is in the debug output I pasted, where the silent install args have blanks where they should have the binroot and cygroot variables interpolated.

This is how `Get-BinRoot` is defined in [ChocolateyHelpers.psm1](https://github.com/OneGet/NuGetProvider/blob/9cd259b1241e940feb820790d82a1c07bfafe6f9/Chocolatey/ChocolateyHelpers.psm1):

```
function Get-BinRoot {
    return $request.GetChocolateyBinRoot();
}
```

Oddly enough, I can't find `GetChocolateyBinRoot` anywhere else in the entire repository. Maybe this is the problem?

**Comment by fearthecowboy** [comment]
Hmm. Somewhere in my refactoring, I seemed to have lost that. Very strange.

I'm building a new community build this morning; let me fix that before I push that out.

**Comment by masaeedu** [comment]
Is the "community build" the master branch or wip?

**Comment by fearthecowboy** [comment]
It will be what's in the WIP branch; as soon as I push it out, I'll push those changes to master. 

Sorry if this is a tad confusing; I did a lot of under-the-covers changes in December, and was trying to stabilize it a bit before pushing it all up to master.

**Comment by fearthecowboy** [comment]
Hmm. Seems I've got a few bits of stupidity in the current code. I'm adding in better tracing messages right now... fixing a few bugs on the fly. Maybe another half hour and I should have it cleaned up.

WRT to the cygwin installer, I've got it calling it correctly now, but the installer itself is giving me a bunch of grief (can't d/l the files? ... even though I can manually grab them ok. ) ...

**Comment by masaeedu** [comment]
D/Ls fine for me. I was using the master builld though (I think it uses OneGet/nuget rather than your new NugetProvider). I do have to be in an elevated shell though.

**Comment by masaeedu** [comment]
Re: your commit an hour ago, you might want to return `PackageExePath` instead of `Path.Combine(RootInstallationPath, "bin")` from the new `ChocolateyBinRoot` prop. (or just get rid of `ChocolateyBinRoot` entirely and just update `Get-BinRoot` to return `PackageExePath` directly)

**Comment by fearthecowboy** [comment]
Ah, yeah, that makes sense. I was probably heading that way when I broke it :)
