### ISSUE TITLE
ProviderSdk could be included as submodule

### ISSUE THREAD

**Issue by masaeedu** [OneGet/OldNuGetProvider#2]
I'm not sure if I'm just misunderstanding how the codebase is structured, but a low priority improvement would be to include ProviderSdk as a submodule of NugetProvider, in order to avoid to duplicate work in two different repos [like](https://github.com/OneGet/ProviderSdk/commit/ad0c040e122dd6246b63b5c9f9b908582335a1a0) [so](https://github.com/OneGet/NuGetProvider/commit/13fad1791789bf4373c13f2fc5912207fce49c36).

---

Sorry about the barrage of issues btw, I really appreciate the work that's going into this project!

**Comment by fearthecowboy** [comment]
The better way to have done it would have been to fork the ProviderSDK and build NuGetProvider on top of that fork.

Unfortunately, I built the NuGet provider first, and the SDK second (based on learning what I did in the NuGet Provider).

that, and the NuGet provider is a waaaay special case.
